### ISSUE TITLE
Update the Sites name and metadata to describe manga-g

### ISSUE THREAD

**Issue by 4cecoder** [manga-g/manga-g#29]
Currently indicates a lot data from the previous project
On actual website the metadata is old and crusty

<img width="818" alt="Screen Shot 2022-05-24 at 5 03 18 PM" src="https://user-images.githubusercontent.com/88108711/170132032-e4ff401a-bf89-44c5-93c3-599abc298bd8.png">

**Comment by whinee** [comment]
This issue has been fixed with my [recent commit](https://github.com/manga-g/manga-g/commit/8b8381d745bbe508ee22546b248d33da7eb199df) to the [site branch](https://github.com/manga-g/manga-g/tree/site), and thus, will now be closed.

Thank you for catching this issue!

---

<h6><i><b><a target="_blank" href="https://github.com/whinee">whi_ne</a> has been paid to help with this project.</b></i></h6>

<h6><i>Want help in your projects too? Inquire through Discord(<a target="_blank" href="https://discord.com/users/867696753434951732">whi_ne (w17e)| whinyaan.xyz#5135</a>) or through e-mail(<a target="_blank" href="mailto:whinyaan@protonmail.com">whinyaan@protonmail.com</a>). Price starts at 50 USD. For commissioning projects, price starts at 30 USD.</i></h6>

---
