### ISSUE TITLE
Make it go install-able

### ISSUE THREAD

**Issue by 4cecoder** [manga-g/manga-g#34]
go install github.com/manga-g/manga-g@latest

**Comment by 4cecoder** [comment]
maybe moving it outside of cmd/core?

or use go workspace and set cmd as a different sub-module so that it would be

**Comment by newbee1905** [comment]
so I just tested with go workspace 
https://github.com/newbee1905/golang-test-workspace
this is just a demo, so now you can install the test script with `go install github.com/newbee1905/golang-test/workspace/gtw@maain`

so maybe instead of cmd/core, maybe move it into a manga-g submodule

with this method, you can let other users use your parser without installing manga-g cmd as well
